[[inputs.mqtt_consumer]]
  servers  = ["${MQTT_URL}"]
  username = "${MQTT_USERNAME}"
  password = "${MQTT_PASSWORD}"

  tls_ca   = "${MQTT_TLS_CA}"
  tls_cert = "${MQTT_TLS_CERT}"
  tls_key  = "${MQTT_TLS_KEY}"
  insecure_skip_verify = false

  topics = ["esp32/discovery/+/config", "tasmota/discovery/+/config"]
  qos = 0
  client_id = "telegraf_mqtt_discovery"
  persistent_session = true
  data_format = "json_v2"

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "esp32/discovery/+/config"
    tags  = "platform/_/serialnumber/_"

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "tasmota/discovery/+/config"
    tags  = "platform/_/serialnumber/_"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "device_config"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "ip"
      rename = "ip"
      type = "string"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "dn"
      rename = "display_name"
      type = "string"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "hn"
      rename = "host_name"
      type = "string"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "mac"
      rename = "mac"
      type = "string"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "md"
      rename = "model"
      type = "string"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "sw"
      rename = "firmware"
      type = "string"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "t"
      rename = "device_topic"
      type = "string"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "ft"
      rename = "full_topic"
      type = "string"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "ofln"
      rename = "offline_text"
      type = "string"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "onln"
      rename = "online_text"
      type = "string"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "ty"
      rename = "type"
      type = "int"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "if"
      rename = "interface"
      type = "int"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "cam"
      rename = "camera"
      type = "int"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "bat"
      rename = "battery"
      type = "int"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "dslp"
      rename = "deep_sleep"
      type = "int"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "ver"
      rename = "version"
      type = "int"
      optional = true
