[[processors.starlark]]
  namepass = [
    "telemetry_sensors",
    "device_state",
    "mqtt_availability",
    "actuator_power",
    "device_config",
    "device_sensors_catalog",
    "command_result",
    "control_action_events"
  ]

  source = '''
def apply(metric):

    # Default fallback
    metric.tags["influx_bucket"] = "iot_state"

    if metric.name == "telemetry_sensors":
        metric.tags["influx_bucket"] = "iot_telemetry"

    elif metric.name in ["device_state", "mqtt_availability", "actuator_power"]:
        metric.tags["influx_bucket"] = "iot_state"

    elif metric.name in ["device_config", "device_sensors_catalog", "command_result"]:
        metric.tags["influx_bucket"] = "iot_meta"

    elif metric.name == "control_action_events":
        metric.tags["influx_bucket"] = "edge_control_events"

    return metric
'''
